<a href="https://colab.research.google.com/github/YudiH11/MSSP6070/blob/master/WeeklyModules/Week05/PARTICIPATION_ACTIVITY_Week_5_Merge_two_Pandas_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata
import os
github_token = userdata.get('Git_Key')
owner = 'YudiH11'
repository = 'MSSP6070'
clone_url = f'https://{owner}:{github_token}@github.com/{owner}/{repository}.git'
!git clone {clone_url}

Cloning into 'MSSP6070'...
remote: Enumerating objects: 205, done.
remote: Counting objects: 100% (205/205), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 205 (delta 88), reused 11 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (205/205), 1.60 MiB | 4.93 MiB/s, done.
Resolving deltas: 100% (88/88), done.

In [4]:
import pandas as pd
aapl = pd.read_csv('aapl.csv')
amzn = pd.read_csv('amzn.csv')
nflx = pd.read_csv('nflx.csv')
fb = pd.read_csv('fb.csv')
goog = pd.read_csv('goog.csv')

In [5]:
# Ticker Column
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
nflx['ticker'] = 'NFLX'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'

In [9]:
faanf = pd.concat([aapl, amzn, nflx, fb, goog])
faanf.to_csv('faanf.csv', index=False)

In [17]:
faanf['date'] = pd.to_datetime(faanf['date'])
faanf['volume'] = faanf['volume'].astype(int)
faanf = faanf.sort_values(['date', 'ticker'])
faanf.head()

        date       open       high        low      close    volume ticker
0 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
0 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
0 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
0 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [13]:
faanf.sort_values('volume', ascending=False).head(7)

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [16]:
faanf_melted = faanf.melt(id_vars=['date', 'ticker'], var_name='variable', value_name='value')
faanf_melted.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000