<a href="https://colab.research.google.com/github/YudiH11/MSSP6070/blob/master/WeeklyModules/Week04/PARTICIPATION_ACTIVITY_Week_4_Opening_a_CSV_file_and_modifying_the_contents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import userdata
import os
github_token = userdata.get('Git_Key')
owner = 'YudiH11'
repository = 'MSSP6070'
clone_url = f'https://{owner}:{github_token}@github.com/{owner}/{repository}.git'
!git clone {clone_url}

Cloning into 'MSSP6070'...
remote: Enumerating objects: 148, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 148 (delta 55), reused 11 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (148/148), 1.21 MiB | 6.16 MiB/s, done.
Resolving deltas: 100% (55/55), done.

In [15]:
import pandas as pd
df = pd.read_csv('/content/MSSP6070/WeeklyModules/Week04/parsed.csv')

In [16]:
#2.A.
japan_mb = df[(df['parsed_place'] == 'Japan') &
              (df['magType'] == 'mb')]
japan_mb['mag'].quantile(0.95)

np.float64(4.9)

In [ ]:
#2.B.
indonesia = df[df['parsed_place'] == 'Indonesia']
tsunami = indonesia['tsunami'].sum()
Total_count = len(indonesia)
percentage = tsunami/Total_count*100
print(percentage)

23.12925170068027

In [17]:
#2.C
nevada = df[df['parsed_place'] == 'Nevada']
nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [23]:
#2.D.
ring_locations = [
    'Bolivia',
    'Chile',
    'Ecuador',
    'Peru',
    'Costa Rica',
    'Guatemala',
    'Mexico',
    'Japan',
    'Philippines',
    'Indonesia',
    'New Zealand',
    'Antarctic',
    'Canada',
    'Fiji',
    'Alaska',
    'Washington',
    'California',
    'Russia',
    'Taiwan',
    'Tonga',
    'Kermadec Islands']
place = '|'.join(ring_locations)
df['parsed_place'].str.contains(place, na = False)
df['ring_of_fire'] = df['parsed_place'].str.contains(place, na = False)
df.loc[df['parsed_place'] == 'New Mexico', 'ring_of_fire'] = False

In [24]:
#2.E
df['ring_of_fire'].value_counts()

ring_of_fire
True     7188
False    2144
Name: count, dtype: int64

In [ ]:
#2.F
df.loc[df['ring_of_fire'], 'tsunami'].sum()

np.int64(45)